step_mul: 8  # 180 APM
screen:  # at least 64^2 resolution is recommended to be playable for regular map
    y_res: 32  # use 32^32 for mini games here
    x_res: 32
minimap:
    y_res: 32
    x_res: 32
